# Generated by Django 4.1.7 on 2023-02-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transanction_id',
            new_name='transaction_id',
        ),
    ]
