# Generated by Django 4.1.7 on 2023-02-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookservices', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discription',
            field=models.TextField(),
        ),
    ]
