# Generated by Django 4.1.7 on 2023-03-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookservices', '0010_remove_order_transaction_id_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
