# Generated by Django 4.1.7 on 2023-03-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookservices', '0012_rename_payment_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_signature_id',
            new_name='razorpay_signature',
        ),
    ]
