# Generated by Django 4.1.7 on 2023-03-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookservices', '0013_rename_razorpay_signature_id_order_razorpay_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
